### ISSUE TITLE
routing url and queries

### ISSUE THREAD

**Issue by loklaan** [demscode/bearded-lama#11]
I'm not sure how the routing works... Could someone clear this up for me?

Is it like `beardedlama.dev/game.aspx?id=9001`?
So, the game view would handle state and routing?

**Comment by Airodin** [comment]
As far as i know the business and data tier deals with that.
If we we're on a page we can call beardedlama.dev/game.aspx?id=9001, which should just send the command 9001 to the asp program to deal with.
We just use it as an input to the program which we then put out whatever we'd like.
(That's my understanding at least.)

**Comment by loklaan** [comment]
Yeah, those queries will be sent off to any business logic, but I think it is first handled by the view (aspx file). These things may be generated though, by VS.

**Comment by loklaan** [comment]
**References:**
- MSDN [routing with url patterns](http://msdn.microsoft.com/en-us/library/cc668201.aspx#adding_routes_to_a_web_forms_application)
- MSDN tutorial [routing in web forms app](http://msdn.microsoft.com/en-us/library/dd329551.aspx)
- MSDN [request querystring collection](http://msdn.microsoft.com/en-us/library/system.web.httprequest.querystring.aspx)

**Comment by loklaan** [comment]
Resembles what #12 will probably look like, as well. Initially, very minimal in length of url and format formality.
![view-routing](https://cloud.githubusercontent.com/assets/1560301/2763076/1f1be398-c9fe-11e3-9e5d-2c3e13211f58.png)
