### ISSUE TITLE
CRUD

### ISSUE THREAD

**Issue by loklaan** [demscode/bearded-lama#14]
_This is an overarching issue._
**CRUD for:**
- [x] users (related to #2)
- [x] games
- [x] game history
- [x] posts (game comments?)
- [ ] chat (the persistent logs, not the active websocket i/o)
- [x] bans (for chat?)

**Comment by loklaan** [comment]
@andresdsep #3 will eventually need access to game history and game CRUD

**Comment by andresdsep** [comment]
Data access and Data classes implemented. Chat table access has been skipped due to our decision  to scrape the chat feature

**Comment by loklaan** [comment]
We'll leave it open because of new reference [#8](https://github.com/knotsoftware/bearded-lama/issues/8#issuecomment-41013534).
