### ISSUE TITLE
Setup login for users

### ISSUE THREAD

**Issue by Airodin** [demscode/bearded-lama#2]
Using the IIS services connected to the Microsoft SQL server

**Comment by loklaan** [comment]
Way to be general :)

**Comment by loklaan** [comment]
We actually have to setup login through Web forms, biz tier and data
access. Just to clarify.

**Comment by loklaan** [comment]
So looking at this in more depth.

The `CreateUserWizard` control uses a `MembershipProvider`, which usually is `System.Web.Security.SqlMembershipProvider`. This provider just needs a connection string and a table that matches its schema.. Thing is, one of Tonys requirements is to separate the presentation from the data access... This user creation control shouldn't have direct access?

So, I think we have a to have implement another Provider in the Business Tier. New class that inherits and overrides most of `System.Web.Security.SqlMembershipProvider` with CRUD @andresdsep made?

@knotsoftware/owners Let me know what you think about this situation.

**Comment by loklaan** [comment]
@knotsoftware/owners We'll implement our own Provider for Members and Roles.

**Comment by loklaan** [comment]
Just figured out I shouldn't be using normal asp Data View controllers for viewing/editing the user details. Because we are using an membership provider as an additional layer between the presentation and user data, we should be using methods from the membership provider in a new user control.
