### ISSUE TITLE
Submission Forms for games

### ISSUE THREAD

**Issue by Airodin** [demscode/bearded-lama#5]
A form which users have access to that they can submit games from.

**Comment by andresdsep** [comment]
Just a button on the user profile page, only visible if you're logged in as that user

**Comment by loklaan** [comment]
The way this will work is:
1. User uploads file with websites fileupload controller.
2. Business tier handles the upload request.  
   1. This uses Data tier storage method to put into a temp folder.
   2. Validation of game submission by biz tier is done from the temp folder.
   3. If validates then use Data tier again to put into permanent public folder, under gameid
3. User then gets validation response back, with any errors in validation failed.
