### ISSUE TITLE
identicons for new users

### ISSUE THREAD

**Issue by loklaan** [demscode/bearded-lama#6]
http://en.wikipedia.org/wiki/Identicon

some free c sharp implementation should be found

**Comment by loklaan** [comment]
Or external web service, which would cover one of the marking criteria. (Demonstrated to Anthony sans fastapps)

**Comment by loklaan** [comment]
Gravatar can be used as an identicon generator. The hash code in the url was from _lochlan_.

![742214af2765181fee9d40eb3e729bb5](https://cloud.githubusercontent.com/assets/1560301/2765284/42ee5ef8-ca22-11e3-867c-0a5e52ac1206.png)
`http://www.gravatar.com/avatar/742214af2765181fee9d40eb3e729bb5?d=retro&f=y`

![742214af2765181fee9d40eb3e729bb5](https://cloud.githubusercontent.com/assets/1560301/2765318/aacf18b4-ca22-11e3-8f26-10737ab1d978.png)
`http://www.gravatar.com/avatar/742214af2765181fee9d40eb3e729bb5?d=monsterid&f=y`

More on it @ [gravatar blog](https://en.gravatar.com/site/implement/images/)

**Comment by loklaan** [comment]
andres @andresdsep 
![231badb19b93e44f47da1bd64a8147f2](https://cloud.githubusercontent.com/assets/1560301/2773482/4392e160-ca9c-11e3-9b7f-645b687e5fa2.png)

matthew @Airodin 
![e6a5ba0842a531163425d66839569a68](https://cloud.githubusercontent.com/assets/1560301/2773487/43962f64-ca9c-11e3-82fb-8ea5d08fa666.png)

**Comment by andresdsep** [comment]
What sorcery is this?!
