### ISSUE TITLE
chat window form

### ISSUE THREAD

**Issue by loklaan** [demscode/bearded-lama#8]
some form to inherit when creating new chat room

**Comment by Airodin** [comment]
Sockets are things that are good and have potential.

**Comment by loklaan** [comment]
websockets! normally people use a js lib called socket.io because it offers
fallback

**Comment by loklaan** [comment]
**References:**
- MSDN [websockets namespace](http://msdn.microsoft.com/en-us/library/system.web.websockets.aspx)
- MSDN Blog [SignalR with IIS 7.5 to handle websockets](http://blogs.msdn.com/b/timlee/archive/2013/03/21/hosting-a-signalr-application-on-windows-2008r2-and-iis-7-5.aspx)
- MSDN [User Controls](http://msdn.microsoft.com/en-us/library/3457w616%28v=vs.100%29.aspx)
